### ISSUE TITLE
How to use mentions

### ISSUE THREAD

**Issue by RAcharya1** [mendhak/Airflow-MS-Teams-Operator#1]
Any chance on implementation of @mentions in msteams?

**Comment by mendhak** [comment]
Doesn't look possible. From what I see, connectors which are used by incoming webhooks, use the [legacy message card format](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference) - which doesn't support mentions.   If there's an overhaul on the Teams side, and incoming webhooks start to use the [adaptive message card format](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card), then there might be the ability to [use <at> for mentions](https://powerusers.microsoft.com/t5/Building-Flows/Ms-Teams-Mentions-in-adaptive-cards/td-p/520520).

**Comment by mendhak** [comment]
The operator has now been overhauled to use AdaptiveCards. Mentions should work. https://adaptivecards.io/
