### ISSUE TITLE
Problem with accents in messages

### ISSUE THREAD

**Issue by michelmetran** [mendhak/Airflow-MS-Teams-Operator#13]
Hello from Brazil!
Very interesting to associate Teams, so popular in corporate environments, with AirFlow!

I noticed that messages containing accents are not rendered well. Probably some issue related to encoding.
![](https://i.imgur.com/z2wJBNJ.png)

Could you give me suggestions to fix!?
I don't have that much knowledge to adjust...

**Comment by mendhak** [comment]
Oh I thought that would have worked automatically. What kind of environment does your Airflow run in, is it Python3 or Python2? I ask because in Python3 I think this is supposedly already taken care of. :confused: 

If you are in Python3, then here is something you can try. Go to this line: 

https://github.com/mendhak/Airflow-MS-Teams-Operator/blob/a370ba59141168ba7058c44760b2a399b650edb6/ms_teams_webhook_hook.py#L133-L136

And change that content type header to: 

    Content-type: application/json; charset=utf-8

So that way you are indicating that it's UTF-8 format data coming in... I hope it works after that. 
If it does work please let me know I can make the change in the code here. Or feel free to make a pull request.

**Comment by michelmetran** [comment]
Thanks for the help!!, but it didn't work...

I tried the suggestion to include the charset definition, but it still didn't work.
```python
self.run(
    endpoint=self.webhook_token,
    data=self.build_message(),
    headers={'Content-type': 'application/json; charset=utf-8'},
    extra_options={'proxies': proxies},
)
```

<br>

To try to "see" if the accents were reaching the AirFlow, I printed the message, adjusting the code.
It is possible to observe that the accents are "coming" to Airflow.
But... now I don't know how to keep trying to solve it...
```python
  def build_message(self):
      cardjson = """
              {{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "{3}",
          "summary": "{0}",
          "sections": [{{
              "activityTitle": "{1}",
              "activitySubtitle": "{2}",
              "markdown": true,
              "potentialAction": [
                  {{
                      "@type": "OpenUri",
                      "name": "{4}",
                      "targets": [
                          {{ "os": "default", "uri": "{5}" }}
                      ]
                  }}
              ],
          }}]
          }}
              """
      msg = cardjson.format(
          self.message,  # 0
          self.message,  # 1
          self.subtitle,  # 2
          self.theme_color,  # 3
          self.button_text,  # 4
          self.button_url,  # 5
      )
      print(msg)
      return msg
```

<br>

The output is...

![Imagem](https://i.imgur.com/8H65psw.png)

**Comment by michelmetran** [comment]
I forgot: I'm using python 3.10!!!

**Comment by mendhak** [comment]
I just had a try, I set the hook ID to point at httpbin.org. 

In the webhook_operator.py, try setting putting .encode('utf-8') against the text fields. For example

```python
        self.hook = MSTeamsWebhookHook(
            self.http_conn_id,
            self.webhook_token,
            self.message.encode('utf-8'),
            self.subtitle.encode('utf-8'),
            self.button_text,
            self.button_url,
            self.theme_color,
            self.proxy
        )
```

When I tested without that, Airflow itself failed and said

> Body ('私のスプーンは大きすぎます') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

What's strange is this seems to indicate that everything is sent over as Latin-1 not UTF-8, but I thought UTF-8 is the default. :confused: 

For completeness my headers looks like this

```
headers={'Content-type': 'application/json; charset=UTF-8'},
```

**Comment by mendhak** [comment]
Thanks for investigating, and the PR! closing this
