### ISSUE TITLE
theme_color is not working. Airflow Version 2.5.3

### ISSUE THREAD

**Issue by PrashanthMaturi323** [mendhak/Airflow-MS-Teams-Operator#17]
used the below script to send teams alert. It's sending alert as expected but color is not displayed on the Card's topline. 

    teams_notification = MSTeamsWebhookOperator(
        task_id="msteams_notify_batch_start", trigger_rule="all_done",
        message=f"**Dag Running**",
        subtitle=f"Task-1 is completed successfully",
        button_text=f'{dag_id}',
        button_url=f'{dag_url}', 
        theme_color="00FF00", 
        http_conn_id='prashanth-webhook')
    teams_notification.execute(context)

![image](https://github.com/mendhak/Airflow-MS-Teams-Operator/assets/111625281/c286048c-7694-4b47-90ad-b4d7822aee00)

**Comment by mendhak** [comment]
Nothing obvious sticks out to me. Can you try playing with the theme_color, eg try adding a `#` even though it's not needed. Or try a few different colors like `000000` or `FF0000`. 

The [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL#example-of-connector-message) still shows color without the `#` so maybe it's not that. 

Just a guess, try enclosing it in _additional_ quotes?

**Comment by PrashanthMaturi323** [comment]
Hello Mendhak, 

Thanks for your reply. I tried with below different cases but no luck. Is there any other additional configuration required at Composer level or Teams (webhook) level?

theme_color="000000"
theme_color="FF0000"
theme_color="#FF0000"
theme_color="'FF0000'"
theme_color="'#FF0000'"

**Comment by mendhak** [comment]
There shouldn't be, I haven't had to do anything like that in my webhooks. Just create the webhook, get a URL. Send a card through.

What you could try, on the [MS documentation page](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL), try the JSON and CURL commands shown. If that works, maybe compare it to what's missing from the operator. 

A good way to see what the operator is sending is just add a [print here](https://github.com/mendhak/Airflow-MS-Teams-Operator/blob/master/ms_teams_webhook_hook.py#L115), and compare the JSON. Or you can use an [HTTP echo container](https://github.com/mendhak/docker-http-https-echo) to see what was sent.

**Comment by PrashanthMaturi323** [comment]
I do have some access issues to test with CURL commands. As you suggested, I tried to print the what operator is sending and noticed that it's sending themeColor also. However, it's not reflecting in the Teams notification. there may be problem with Teams only. Anyway thanks for your suggestions!

![image](https://github.com/mendhak/Airflow-MS-Teams-Operator/assets/111625281/4c149a14-60da-4ee1-89c5-debc087de10c)
