### ISSUE TITLE
Cloud Composer - 'Host' Data Too Long

### ISSUE THREAD

**Issue by RickRen7575** [mendhak/Airflow-MS-Teams-Operator#2]
I am trying to create a Connection in my managed Airflow service - GCP's Composer. However, when trying to create the connection, Airflow is letting me know that the data is too long in the column 'host'. Here is part of the error without the actual Webhook URI attached:

![image](https://user-images.githubusercontent.com/8716030/113191104-28c23f80-922b-11eb-9276-682cffb7d3b9.png)

Do you know if there is a way to fix this in Composer? I cannot access the database since it is managed by GCP.

**Comment by mendhak** [comment]
I'm not familiar with Composer, or GCP.  However from what I know it's Airflow that creates the DB, unless GCP have somehow decided to alter the creation?  

Reason for mentiong it - does it work if you try in a local Airflow with a local MySql? If it works locally but not in Composer then maybe that's some limitation they've introduced in their implementation.

**Comment by rotsmi** [comment]
@RickRen7575 you can resolve that limitation separating the full webhook teams url by the `http_conn_id ` and `webhook_token` when calling the `MSTeamsWebhookOperator` operator:

```
teams_notification = MSTeamsWebhookOperator(
        task_id="notify_failure",
        http_conn_id="<your-webhook-teams-domain (https://xyz.webhook.office.com)>",
        webhook_token="<the webhook url part after the domain (/webhookb2/string/IncomingWebhook/string)>",
        ...
    )
    teams_notification.execute(context)
```

Hope that helps!
