### ISSUE TITLE
Host URL too long

### ISSUE THREAD

**Issue by mihailgag** [mendhak/Airflow-MS-Teams-Operator#9]
Hi, I'm using Airflow 1.10.15, hosted on a GCP composer, so I was trying to make a http connection to MSTeams, while adding the webook url into the Host field got this error:

Failed to create record. (_mysql_exceptions.DataError) (1406, "Data too long for column 'host' at row 1") [SQL: INSERT INTO connection (conn_id, conn_type, host, `schema`, login, password, port, is_encrypted, is_extra_encrypted, extra) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)] [parameters: ('http_teams_hook', 'http', 'https://***.webhook.office.com/webhookb2/29762ac4-****-****-****-bc12c6fb788e@efce8346-****-****-****-0fd07bd5e442/IncomingWebhook/32287185d66a4813b4cbd78914e01cab/8094d090-****-****-****-*************', None, None, None, None, 0, 0, '')] (Background on this error at: http://sqlalche.me/e/13/9h9h)

**Comment by mendhak** [comment]
From the little searching I did, this seems to be some kind of limitation related to the DB setup for MySQL.  Whatever the schema is that's been set up is too tiny to hold the massive MS Teams webhook URLs that get generated.
